name: deploy

on: push
  # push:
  #   branches:
  #     - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: node:lts-alpine
    steps:
      - uses: actions/checkout@v2
      - name: Install tar
        run: apk add --update-cache tar
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/cache@v2
        id: yarn-cache
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: yarn-v1-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-v1-${{ runner.os }}-
      - name: Install npm packages
        run: yarn install --frozen-lockfile
      - name: Build
        run: yarn build:production
